# Generated by Django 4.1 on 2022-09-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0002_country_programa_tipoproceso_remove_procesos_pro_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='19:59:58', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
