# Generated by Django 4.1.1 on 2022-12-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_caracterizacion', '0004_alter_procesos_fec_pro_alter_procesos_hor_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='fec_pro',
            field=models.CharField(default='2022/12/19', editable=False, max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hor_pro',
            field=models.CharField(default='22:01:36', editable=False, max_length=50, verbose_name='Hora'),
        ),
    ]
